VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.box_check_update = false

  config.vm.hostname = "www.sammui.dev"

#  config.vm.network "private_network", type: "dhcp"
  config.vm.network "private_network", ip: "10.1.1.9"
  config.vm.network :forwarded_port, guest: 80, host: 8365

  config.vm.synced_folder ".", "/vagrant", owner: "www-data", group: "www-data", mount_options: ["dmode=777,fmode=776"]
  config.vm.synced_folder "/home/renatomefi/WS/sammui", "/home/sammui/project", owner: "www-data", group: "www-data", mount_options: ["dmode=777,fmode=776"]

  config.vm.provider "virtualbox" do |vb|
     vb.customize ["modifyvm", :id, "--memory", "900"]
     vb.customize ["modifyvm", :id, "--cpus", "2"]
  end

  config.vm.provision "shell",
    path: "/home/renatomefi/WS/sammui/bin/vagrant/provision.sh"

  config.vm.provision "shell",
    inline: "service nginx restart",
    run: "always"

end
